FROM jboss/wildfly

#
# create an admin user
#
# RUN /opt/jboss/wildfly/bin/add-user.sh admin Admin#70365 --silent

#
# add war file to deployments dir
#
ADD contents/node-info.war /opt/jboss/wildfly/standalone/deployments/

