---
#
# https://docs.openshift.com/container-platform/3.3/dev_guide/builds.html#jenkinsfile
#
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "wildfly-demo-app-pipeline"
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/rossillingworth/node-info"
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile

